title          : "Introduction to DataCamp Projects (R)"
description    : >
  If you've never done a DataCamp project, this is the place to start! 
language       : r
from           : 'r-notebooks-prod:36'
runtime_config : default
state          : development
long_description: |
  This is an introduction to DataCamp projects. A DataCamp project will allow you to practice and 
  apply the skills you've learned in the DataCamp courses. In each project you will carry out an 
  end-to-end analysis, on a real-world task, using real-world tools and workflows. 
  In this gentle introduction to DataCamp projects, we will walk you through the projects
  interface and you will learn how to work with Jupyter notebooks: 
  an open-source web application that is great for interactive data analysis.
technology: 1
instructors:
  - rasmus@datacamp.com
collaborators:
  - ramnath@datacamp.com
  - martijn@datacamp.com
topics:
  - 1
  - 4
  - 12
prerequisites:
  - 58
  - 672
difficulty_level: 1
time_needed: "30 minutes"
illustration: "https://s3.amazonaws.com/assets.datacamp.com/production/project_41/datasets/project_image.png"

